### ISSUE TITLE
install from pip

### ISSUE THREAD

**Issue by Hellfar** [benoitc/http-parser#56]
Hello,

It seems that the [install of the http-parser through pip](https://pypi.python.org/pypi/http-parser#installation) gets wrong while it tries to reach https://pypi.python.org/simple/http-parse/ since it should be https://pypi.python.org/simple/http-parser/ .

See (the log /home/userHome/.pip/pip.log):
Getting page https://pypi.python.org/simple/http-parse/
  Could not fetch URL https://pypi.python.org/simple/http-parse/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/http-parse/ when looking for download links for http-parse
            .....

Still, I am a very newbie, so not sure if I am not saying anything stupid.

Regards.
Hellfar.

**Comment by liuyangc3** [comment]
Hi,

I was using pip install this lib,and got an UnicodeEncodeError:
```
Collecting http-parser                                                                                    
  Using cached http-parser-0.8.3.tar.gz                                                                   
Installing collected packages: http-parser                                                                
  Running setup.py install for http-parser ... error                                                      
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\u
setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, '
v0bu-record\install-record.txt --single-version-externally-managed --compile:                             
    running install                                                                                       
    running build                                                                                         
    running build_py                                                                                      
    creating build                                                                                        
    creating build\lib.win-amd64-2.7                                                                      
    creating build\lib.win-amd64-2.7\http_parser                                                          
    copying http_parser\http.py -> build\lib.win-amd64-2.7\http_parser                                    
    copying http_parser\pyparser.py -> build\lib.win-amd64-2.7\http_parser                                
    copying http_parser\reader.py -> build\lib.win-amd64-2.7\http_parser                                  
    copying http_parser\util.py -> build\lib.win-amd64-2.7\http_parser                                    
    copying http_parser\_socketio.py -> build\lib.win-amd64-2.7\http_parser                               
    copying http_parser\__init__.py -> build\lib.win-amd64-2.7\http_parser                                
    running build_ext                                                                                     
    building 'http_parser.parser' extension                                                               
    Traceback (most recent call last):                                                                    
      File "<string>", line 1, in <module>                                                                
      File "c:\users\web\appdata\local\temp\pip-build-ubzdm8\http-parser\setup.py", line 160, in <module> 
        run_setup(not IS_PYPY)                                                                            
      File "c:\users\web\appdata\local\temp\pip-build-ubzdm8\http-parser\setup.py", line 155, in run_setup
        ** extra                                                                                          
      File "c:\python27\lib\distutils\core.py", line 166, in setup                                        
        raise SystemExit, "error: " + str(msg)                                                            
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-10: ordinal not in range(128) 
```

**Comment by petri** [comment]
I think this issue is invalid and can be closed.

**Comment by Hellfar** [comment]
@petri, @liuyangc3 issue is different from mine.
There WAS a typing errors in the installation process with `pip`, but it's fixed now.
Just tried again, with the same machine and everything's fine :slightly_smiling_face: .
