### ISSUE TITLE
Python 3.12 installation fails

### ISSUE THREAD

**Issue by kasium** [benoitc/http-parser#99]
```
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-btpgg84o/http-parser_a6c14b2ad3cd4d90a8e000168824cb8d/setup.py", line 12, in <module>
          from imp import load_source
      ModuleNotFoundError: No module named 'imp'
      [end of output]
```

`imp` is deprecated and was removed with 3.12

**Comment by add-n2x** [comment]
Ran into this today. Currently not able to install `http-parser` anymore.
